### ISSUE TITLE
Last commit "Rejigger some of the trigger lookup code" broke snipmate

### ISSUE THREAD

**Issue by yann-morin-1998** [garbas/vim-snipmate#181]
I updated to latest vim-snipmate, and vim now complains a lot.

The simplest test-case is to start with an empty file, go to insert mode, and just press TAB:

    Error detected while processing function snipMate#TriggerSnippet..snipMate#GetSnippetsForWordBelowCursor:
    line    5:
    E684: list index out of range: 0
    Press ENTER or type command to continue
    Error detected while processing function snipMate#TriggerSnippet..snipMate#GetSnippetsForWordBelowCursor:
    line    5:
    E116: Invalid arguments for function len(parts[0]) > 1
    Press ENTER or type command to continue
    Error detected while processing function snipMate#TriggerSnippet..snipMate#GetSnippetsForWordBelowCursor:
    line    5:
    E15: Invalid expression: len(parts[0]) > 1
    Press ENTER or type command to continue

Of course, the issue occurs about anytime one presses TAB and there is no snippet to complete, which in my case is rather more often than not.

I bisected the problem, and 29c01b723 is the first bad commit. Reverting it indeed fixes the issue.

Regards,
Yann E. MORIN.

**Comment by fourjay** [comment]
On my own snippets the update works. I think the problem is in conjunction with the (parallel) snippets package. Rather suspect there's some format change that the stock bundle of snippets won't work with. But also wanted to chime in that I'm seeing similar issues.

**Comment by ajzafar** [comment]
@yann-morin-1998 Can you share the name(s) of snippet(s) which cause the error? I have an idea what the problem is but am having trouble reproducing. Also did you mean that 0e460296 is the last bad commit, the one in the issue title?

**Comment by yann-morin-1998** [comment]
@ajzafar How can I know which snippet causes the issue?

The traces I added in the report are all I can see; there is no other output.

As @fourjay suggested, I am using the snippets from https://github.com/honza/vim-snippets.git up-to-date as of right now. I also have a few curtom snippets, too. Do you want them? Where should I put them?

As for the commit ID, I messed up the report, and I really meant that 29c01b7 is the last good commit, and as you replied, 0e46029 is the first bad commit.

But since I posted the report, I encountered a similar issue, so I have to test-cases that fail in a similar fashion.

For completion on the empty file, 0e46029 is the first bad commit, as reported.

Now, reverting 0e46029 and editing an empty file, go to edit mode, add a pipe | and press TAB:

    Error detected while processing function snipMate#TriggerSnippet..snipMate#GetSnippetsForWordBelowCursor..funcref#Call..snipMate#GetSnippets
    ..funcref#Call..snipMate#DefaultPool:
    line   13:
    =snipMate#ShowAvailableSnips()
    Error detected while processing function snipMate#ShowAvailableSnips..snipMate#GetSnippetsForWordBelowCursorForComplete..snipMate#    GetSnippetsForWordBelowCursor..funcref#Call..snipMate#GetSnippets..funcref#Call..snipMate#DefaultPool:
    line   13:
    E20: Mark not set
    Press ENTER or type command to continue

So I bisected that one, too, and 8598c5ad is the first bad commit.

**Comment by ajzafar** [comment]
@yann-morin-1998 Ah sorry, I misread part of the report. I pushed a fix for the empty file problem.

**Comment by yann-morin-1998** [comment]
@ajzafar No problem, I did a mistake in the report, so that's my fault. ;-)

I tested the fix for the empty file: works as expected, thanks.

The other test-case still fails, however.

**Comment by ajzafar** [comment]
Alright, pushed a fix for the other problem. Thanks for the reports!

**Comment by yann-morin-1998** [comment]
@ajzafar OK, both issues now indeed fixed. Thanks for the quick response and small round-trip time! :-)
