### ISSUE TITLE
C Snippet Error: E121: Undefined variable: v:key

### ISSUE THREAD

**Issue by zachwhaley** [garbas/vim-snipmate#185]
When I attempt to expand a C snippet I get this error
```
Error detected while processing function snipMate#TriggerSnippet..snipMate#GetSnippetsForWordBelowCursor..funcref#Call..snipMate#GetSnippets..funcref#Call..snipMate#DefaultPool..<SNR>81_snippet_filenames:
E121: Undefined variable: v:key
```

When I type Enter Vim continues to detect errors, and when I press Esc Vim goes berserk and spews lines of errors preventing me from exiting.

8598c5adecd5035b9f6bea3d5bb72b3f286e6d20 by @ajzafar introduced the issue for me
 
Pic of the first error
![undefined-variable-v key](https://cloud.githubusercontent.com/assets/2996465/6031499/7c2d3b28-abc5-11e4-9bec-477df5172360.png)

Pic of the spewing errors
![snipmate-error-spewing](https://cloud.githubusercontent.com/assets/2996465/6031772/cc2c58e6-abc7-11e4-9436-cb71cda661ec.png)

```
$ vim --version
VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Jan 28 2015 17:05:59)
Compiled by build@ajax
Big version without GUI.  Features included (+) or not (-):
+arabic +autocmd -balloon_eval -browse ++builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
+cryptv +cscope +cursorshape +dialog_con +diff +digraphs -dnd -ebcdic 
+emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path +find_in_path 
+float +folding -footer +fork() -gettext -hangul_input +iconv +insert_expand 
+jumplist +keymap +langmap +libcall +linebreak +lispindent +listcmds +localmap 
+menu +mksession +modify_fname +mouse -mouseshape +mouse_dec -mouse_gpm 
-mouse_jsbterm +mouse_netterm -mouse_sysmouse +mouse_xterm +multi_byte 
+multi_lang -mzscheme -netbeans_intg -osfiletype +path_extra -perl +postscript 
+printer -profile -python +quickfix +reltime +rightleft -ruby +scrollbind 
+signs +smartindent -sniff +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: 
gcc -c -I. -Iproto -DHAVE_CONFIG_H   -I/usr/local/include  -g -O2        
Linking: gcc   -L/usr/local/lib -o vim       -lm -lncurses -ldl
```

**Comment by ajzafar** [comment]
Hmm I think this might be due to your relatively old Vim version as I'm unable to reproduce this. The only thing I could find that might be the cause is what was fixed in [patch 7.3.155](https://groups.google.com/forum/#!topic/vim_dev/2fyfcCVk4aw). I think this means the error would occur every time you tried to trigger a snippet, but I'm not sure. Regardless, I just pushed a potential fix. Could you try pulling from master and reporting back, @zachwhaley?

**Comment by zachwhaley** [comment]
Sorry about the old Vim version.  This is on a shared host, so I don't have much control in that regard.

Yes, the error does occur with any snippet.

I've pulled from master and I'm still getting the same error, but the error spewing has stopped :-)

I'll try my best to see if I can create a fix, but no promises (I know very little vimscript)

**Comment by ajzafar** [comment]
@zachwhaley Ah, drats. Let me know if there's anything else I can do. If I find some time I might try and build Vim 7.2 to get a better handle on it.

**Comment by ajzafar** [comment]
@zachwhaley Somehow I missed [patch 7.2.295](http://ftp.vim.org/editors/vim/patches/7.2/7.2.295), which fixes the Vim bug you're experiencing. I pushed a workaround that avoids using `v:key`, so it should work now.

**Comment by zachwhaley** [comment]
Thanks!  

I'll test it out tomorrow and close the issue if it works.

**Comment by zachwhaley** [comment]
Fixed with 90d568bc4faef8b8c3f4ada6141bc44d22fa5b03
